import { DEV_SERVER_STARTUP_GUIDANCE } from '@codebuff/common/constants/dev-server-guidance'

/** Standing Sites guidance shared by Desktop and Cloud harnesses, never per-step injection. */
export function sitesGuidance(
  mode: 'plan' | 'build',
  runtime: 'desktop' | 'cloud' = 'desktop',
): string {
  if (mode === 'plan')
    return `# Sites: Cloudflare, auth, and storage
Use sites_list/sites_inspect to understand existing sites. Plan compatible Worker deployments, D1/R2 storage, and @freebuff/auth integration, but do not provision, deploy, or change secrets in plan mode.`
  return `# Sites: Cloudflare, auth, and storage

Use sites_* tools for agent-managed hosting when the user requests it. Keep the site ID in the workspace, inspect existing resources before creating more, and target preview first. Production publishing needs the user's authorization; preview URLs are also public.

${runtime === 'cloud' ? 'When website changes are ready for review, start a dev server in the VM bound to 0.0.0.0 and use cloud_show_dev_server with its port. Follow the Cloud preview networking instructions. A dev-server preview is not a deployment and does not establish Workers compatibility.' : 'When website changes are ready for user review, first show the running dev server using register_preview in the right-side browser panel before offering or attempting a preview deployment. Use a loopback URL and the owned server PID. Install dependencies and start the server only when needed. Reuse a running server, keep hot reload working, and skip this for non-web projects or when the user asks not to preview. A dev-server preview is not a deployment and does not establish Workers compatibility. If preview setup fails, report the blocker rather than silently deploying instead.'}

${runtime === 'desktop' ? DEV_SERVER_STARTUP_GUIDANCE : ''}

Compatibility: deploy prebuilt Cloudflare Worker fetch handlers (ES modules, optionally bundled WASM) plus static assets. Static HTML and Vite/React/Vue/Svelte frontends work with a Worker serving env.ASSETS.fetch(request); Hono and other Workers-compatible fetch frameworks work server-side. Bundle dependencies locally. The backend does not build source or run npm, Node/Bun servers, containers, Python, native addons, persistent filesystems, or background daemons. nodejs_compat is limited compatibility, not a Node server. Next.js SSR and other SSR frameworks require a verified Workers adapter and output matching the deploy manifest; do not upload a normal .next build or assume arbitrary adapter bindings are supported. Prefer a static frontend plus a small Worker for new sites.

Storage: sites_add_storage provisions D1 (SQLite SQL via env.DB) or R2 (objects via env.FILES), isolated by preview/production. These are Workers bindings, not browser SDKs or PostgreSQL connections. Query them on the server; use bound SQL parameters. Initialize/migrate the D1 schema through controlled server-side code and test with local Wrangler D1/R2 first; there is no arbitrary SQL-write tool. Deploy after provisioning to attach bindings. Use D1/R2 for persistent user data; isolate-local Maps and arrays are disposable demo state.

Auth: when login/accounts/per-user data are requested, use sites_enable_auth${runtime === 'desktop' ? " with the local Worker's loopback origin" : ''}, then install @freebuff/auth and read node_modules/@freebuff/auth/AGENTS.md. If the package or issuer is unavailable, report the setup blocker; never invent credentials. ${runtime === 'cloud' ? 'VM loopback addresses are not reachable by the user’s browser: omit localOrigin for hosted auth and verify browser sign-in on the deployed preview origin. ' : ''}Its fetch SDK works in Workers/Hono (also Bun/Deno); its Next.js adapter does not make Next.js automatically deployable here. A browser-only/static app needs a server Worker for auth. Wrap the handler once per isolate before API/static fallbacks using createFreebuffAuth({ clientId: env.FREEBUFF_CLIENT_ID, issuer: env.FREEBUFF_ISSUER, baseUrl: env.APP_ORIGIN }). These reserved public variables are injected on deploy; use returned development.variables locally, with allowInsecureLocalhost only for loopback development. Never derive baseUrl from a request Host. Preview and production share the OIDC production client with exact callbacks; localhost has a separate development client. No client secret is needed.

Protect every private API with getUser, scope D1 queries/R2 ownership by user.sub (never client-supplied IDs or email), check membership for shared resources, and check isSameOriginRequest for mutations. Personalized responses must be private/no-store. Keep platform credentials and session tokens out of project files, browser storage, logs, and assets. For third-party API keys, direct the user to Sites → Secrets so values stay out of chat. Alternatively use sites_set_secret with a user-provided private file; never read/print its value or put it in chat. Deploy once before setting secrets. The project limit is 25 customer variables across preview and production (the same name in both counts twice); reserved auth variables do not count. Inspect names before adding more, and reuse existing names for rotation.

Before even a preview deployment, build and test locally using wrangler dev/Miniflare (workerd) with the deployment compatibility date, flags, assets, and local bindings. A Node/Bun server or fetch shim alone does not verify Workers compatibility. Check routes/assets, D1/R2 behavior, signed-out 401s, a complete sign-in/callback/session/sign-out flow, two-account data isolation, and foreign-Origin 403s. Report checks blocked by missing accounts or setup; a sign-in redirect alone is not a completed login test. Upload only dedicated public build output via sites_deploy's manifest; keep secrets and source maps out. After the receipt succeeds, open the preview in a browser, check console/network errors and HTML/JS/CSS content types, and repeat the auth checks on its actual origin. HTTP 200 or a successful upload alone does not prove the site renders or auth works. If auth returns 503, inspect safe server diagnostics and reproduce in workerd; do not infer tunnel failure from a generic SDK error or weaken redirect/issuer validation. Distinguish deployed from verified working, and report remaining failures explicitly. Reuse requestId for transport retries; inspect running/unknown operations instead of blindly retrying or switching environments.${runtime === 'cloud' ? '\n\nCloud can show a dev-server preview but has no browser automation tools. Complete available workerd/HTTP checks, then ask the user to perform interactive browser and sign-in checks. Report these checks as pending until the user confirms them; do not claim a complete browser test from HTTP responses alone.' : ''}`
}
